---
name: terraform
on:
  pull_request:
    branches:
      - master
jobs:
  tfformat:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        name: Checkout source code

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.1

      - name: Check against terraform configuration
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

  tflint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    needs: tfformat
    steps:
      - uses: actions/checkout@v2
        name: Checkout source code
      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: v0.28.0
      - name: Show version
        run: tflint --version
      - name: Run TFLint
        run: tflint -f compact
